baseURL = "https://www.dpnb.de"
languageCode = "de-de"
title = "DPNB"
theme = "dpnb"

defaultContentLanguage = "de"

[params.info]
homeTitle = "DPNB - Broker für dynamische Produktionsnetzwerke"


[languages]
  [languages.de]
    LanguageName = "Deutsch"
    weight = 0

  [languages.en]
    LanguageName = "English"
    weight = 1

  [[languages.de.menu.main]]
    url    = "/"
    name   = "Startseite"
    weight = 1

  [[languages.de.menu.main]]
    url    = "/dpnb/"
    identifier = 'project'
    name   = "Das Projekt"
    weight = 2
    hasChildren = true

  [[languages.de.menu.main]]
    url    = "/dpnb/motivation/"
    name   = "Motivation & Idee"
    parent = 'project'
    weight = 1

  [[languages.de.menu.main]]
    url    = "/dpnb/projektpartner/"
    name   = "Projektpartner"
    parent = 'project'
    weight = 2


  [[languages.de.menu.main]]
    url    = "/dpnb/inhalt/"
    name   = "Inhalt"
    parent = 'project'
    weight = 3

  [[languages.de.menu.main]]
    url    = "/aktuelles/"
    name   = "Aktuelles"
    weight = 3

  [[languages.de.menu.main]]
    url    = "/kontakt/"
    name   = "Kontakt"
    weight = 5



  [[languages.en.menu.main]]
    url    = "/"
    name   = "Home"
    weight = 1

  [[languages.en.menu.main]]
    url    = "/dpnb/"
    name   = "Project"
    weight = 2
    identifier = 'project'
    hasChildren = true

  [[languages.en.menu.main]]
    url    = "/dpnb/motivation/"
    name   = "Motivation & idea"
    parent = 'project'
    weight = 1

  [[languages.en.menu.main]]
    url    = "/dpnb/projectpartner/"
    name   = "Project partners"
    parent = 'project'
    weight = 2

  [[languages.en.menu.main]]
    url    = "/dpnb/structure/"
    name   = "Structure"
    parent = 'project'
    weight = 3

  [[languages.en.menu.main]]
    url    = "/aktuelles/"
    name   = "News"
    weight = 3

  [[languages.en.menu.main]]
    url    = "/kontakt/"
    name   = "Contact"
    weight = 5

  [[languages.de.menu.footer]]
    url    = "/impressum/"
    name   = "Impressum"
    weight = 1
	
  [[languages.de.menu.footer]]
    url    = "/datenschutz/"
    name   = "Datenschutz"
    weight = 1
	
  [[languages.en.menu.footer]]
    url    = "/datenschutz/"
    name   = "Privacy Notice"
    weight = 1	

  [[languages.en.menu.footer]]
    url    = "/impressum/"
    name   = "Imprint"
    weight = 1
